package com.my.blog.website.model;

import java.io.Serializable;
import java.util.Date;

public class JordonMap implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jordon_map.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jordon_map.k
     *
     * @mbggenerated
     */
    private String k;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jordon_map.v
     *
     * @mbggenerated
     */
    private String v;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jordon_map.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jordon_map
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jordon_map.id
     *
     * @return the value of jordon_map.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jordon_map.id
     *
     * @param id the value for jordon_map.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jordon_map.k
     *
     * @return the value of jordon_map.k
     *
     * @mbggenerated
     */
    public String getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jordon_map.k
     *
     * @param k the value for jordon_map.k
     *
     * @mbggenerated
     */
    public void setK(String k) {
        this.k = k == null ? null : k.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jordon_map.v
     *
     * @return the value of jordon_map.v
     *
     * @mbggenerated
     */
    public String getV() {
        return v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jordon_map.v
     *
     * @param v the value for jordon_map.v
     *
     * @mbggenerated
     */
    public void setV(String v) {
        this.v = v == null ? null : v.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jordon_map.update_time
     *
     * @return the value of jordon_map.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jordon_map.update_time
     *
     * @param updateTime the value for jordon_map.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}